
2014-11-30T11:49:49: Start analysis
2014-11-30T11:49:52: [ERROR] Analysis failed
System.InvalidOperationException: Cannot obtain list of files ---> System.UnauthorizedAccessException: Access to the path 'F:\Wheel\python\moonbuck\moonbuck\env\Lib' is denied.
   at System.IO.__Error.WinIOError(Int32 errorCode, String maybeFullPath)
   at System.IO.FileSystemEnumerableIterator`1.CommonInit()
   at System.IO.FileSystemEnumerableIterator`1..ctor(String path, String originalUserPath, String searchPattern, SearchOption searchOption, SearchResultHandler`1 resultHandler, Boolean checkHost)
   at System.IO.Directory.EnumerateFiles(String path)
   at Microsoft.PythonTools.Analysis.ModulePath.<GetModuleNamesFromPathHelper>d__0.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   at System.Linq.Enumerable.<ConcatIterator>d__71`1.MoveNext()
   at System.Linq.Lookup`2.Create[TSource](IEnumerable`1 source, Func`2 keySelector, Func`2 elementSelector, IEqualityComparer`1 comparer)
   at System.Linq.GroupedEnumerable`3.GetEnumerator()
   at System.Linq.Enumerable.WhereSelectEnumerableIterator`2.MoveNext()
   at System.Collections.Generic.List`1..ctor(IEnumerable`1 collection)
   at System.Linq.Enumerable.ToList[TSource](IEnumerable`1 source)
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Prepare()
   --- End of inner exception stack trace ---
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Prepare()
   at Microsoft.PythonTools.Analysis.PyLibAnalyzer.Main(String[] args)
